env:
  browser: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
parser: 'babel-eslint'
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  arrow-parens:
    - error
    - as-needed